# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - Roang-zero1
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
      timezone: "Europe/Vienna"
