name: Reusable hadolint workflow

on: workflow_call

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the hadolint
        uses: hadolint/hadolint-action@v3.0.0
