name: lint & release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  actionlint:
    uses: ./.github/workflows/actionlint.yml
  release:
    uses: ./.github/workflows/create-release.yml
