name: Reusable sh-checker workflow

on:
  workflow_call:
    inputs:
      shfmt_args:
        description: Arguments to be passed along to the shfmt call.
        required: false
        type: string
        default: -i 2 -ci

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.7.0
        env:
          SHFMT_OPTS: ${{ inputs.shfmt_args }}
